import { GoogleGenerativeAI } from '@google/generative-ai';

export interface MarketingPackage {
  title: string;
  description: string;
  tags: string[];
  category: string;
  viralityScore: number;
}

export class MarketingService {
  
  static async generatePackage(apiKey: string, scriptContent: string, currentTitle: string): Promise<MarketingPackage> {
    const genAI = new GoogleGenerativeAI(apiKey);
    const model = genAI.getGenerativeModel({ 
        model: 'gemini-2.0-flash',
        generationConfig: { responseMimeType: "application/json" }
    });

    const PROMPT = `
      You are a YouTube Growth Expert. Generate the metadata for this video.
      
      CONTEXT (Current Title): "${currentTitle}"
      SCRIPT CONTENT: 
      "${scriptContent.slice(0, 5000)}..." (truncated)

      INSTRUCTIONS:
      1. TITLE: Must be click-baity but honest. Under 60 chars. High CTR.
      2. DESCRIPTION: First 2 lines must be the "Hook". Include 3 timestamps based on the script flow.
      3. TAGS: 15 relevant, high-volume search tags.
      4. SCORE: Predict the virality (0-100).

      OUTPUT JSON:
      {
        "title": "...",
        "description": "...",
        "tags": ["tag1", "tag2"],
        "category": "Education",
        "viralityScore": 85
      }
    `;

    try {
        const result = await model.generateContent(PROMPT);
        return JSON.parse(result.response.text());
    } catch (e) {
        console.error("Marketing Gen Failed", e);
        return {
            title: currentTitle,
            description: "Generated by AI Creator Studio",
            tags: ["AI", "Video"],
            category: "Entertainment",
            viralityScore: 50
        };
    }
  }
}
