import { NextResponse } from 'next/server'
import { supabaseAdmin } from '@/lib/supabaseServer'

export async function GET(req: Request) {
  const { searchParams } = new URL(req.url)
  const projectId = searchParams.get('projectId')

  if (!projectId) return NextResponse.json({ error: 'No Project ID' }, { status: 400 })

  try {
    // 1. Fetch all project data
    const { data: project } = await supabaseAdmin.from('projects').select('*').eq('id', projectId).single()
    const { data: scenes } = await supabaseAdmin.from('scenes').select('*').eq('project_id', projectId).order('sequence_order')
    const { data: knowledge } = await supabaseAdmin.from('project_knowledge').select('*').eq('project_id', projectId)

    if (!project) throw new Error("Project not found")

    // 2. Build the Markdown Content (The "Readable" Part)
    let content = `# 🎬 PRODUCTION BIBLE: ${project.title}\n\n`
    content += `## 📋 CONCEPT OVERVIEW\n`
    content += `**Target Length:** ${project.target_duration || 'Standard'}\n`
    content += `**Thumbnail Concept:** ${project.thumbnail_url?.startsWith('http') ? `[View Image](${project.thumbnail_url})` : 'Not generated'}\n\n`

    content += `## 🧠 RESEARCH & KNOWLEDGE\n`
    if (knowledge && knowledge.length > 0) {
      knowledge.forEach(k => { content += `* ${k.content}\n` })
    } else {
      content += `*No research notes recorded.*\n`
    }

    content += `\n## ✍️ THE SCRIPT\n`
    content += `| # | VISUAL DIRECTION | AUDIO / VOICEOVER |\n`
    content += `|---|------------------|-------------------|\n`
    
    scenes?.forEach((s, i) => {
      const visual = s.visual_description.replace(/\|/g, '-') // Clean pipes
      const audio = s.audio_text.replace(/\|/g, '-')
      content += `| ${i + 1} | ${visual} | ${audio} |\n`
    })

    content += `\n\n---\n*Generated by AI Creator Studio v2026*`

    // 3. Return as a downloadable file
    return new NextResponse(content, {
      headers: {
        'Content-Type': 'text/markdown',
        'Content-Disposition': `attachment; filename="${project.title.replace(/[^a-z0-9]/gi, '_')}_Bible.md"`,
      },
    })

  } catch (error: any) {
    return NextResponse.json({ error: error.message }, { status: 500 })
  }
}
